[project]
name = "ntcpycon"
version = "0.1.0"
description = "Connects alex-ong/NESTrisOCR to timotheeg/nestrischamps"
authors = [
    {name = "zohassadar", email = "zohassadar@gmail.com"},
]
dependencies = ["pyyaml>=6.0.2", "websockets>=14.2", "scapy>=2.6.1", "pyserial>=3.5", "python-edlinkn8==0.0.2"]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[tool.setuptools]
packages = ["ntcpycon"]

[project.scripts]
ntcpycon = 'ntcpycon.connect:start_connect'
ed2ntc = 'ntcpycon.ed2ntc:main'

[tool.pdm]
distribution = true

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
